### ISSUE TITLE
Problème de double victime dans  `puller.extract_timelines`

### ISSUE THREAD

**Issue by lucgiffon** [Schluucht/Destiny#1]
J'(obtiens l'erreur suivante:

**Comment by lucgiffon** [comment]
Ok, fausse manip au dessus, désolé:

J'obtiens l'erreur suivante:

```
Traceback (most recent call last):
  File "/home/luc/shrdpart/Documents/PROJETS/Destiny/puller.py", line 303, in <module>
    extract_data(cnx)
  File "/home/luc/shrdpart/Documents/PROJETS/Destiny/puller.py", line 152, in extract_data
    extract_timelines(cnx)
  File "/home/luc/shrdpart/Documents/PROJETS/Destiny/puller.py", line 285, in extract_timelines
    victim = CHAMPIONS[str(participants[events['victimId']])]
KeyError: "{'champId': 35}"
```

Pour reproduire:

- clone la branche improve_events_extractor
- run

Ce que j'en ai compris:

- Ca a lieu lors de la récupération d'un event `CHAMPION_KILL` et de la récupération des victimes du kill. 
- Lorsqu'il y a plusieurs victimes: on a un dictionnaire dans chaque entrée de participants[events['victimId'] et pas un id, il est casté en string et on obtient juste après l'erreur car la string `"{'champId': 35}"` n'est pas dans le dictionnaire `CHAMPIONS`.


Ca me semble bizarre que tu n'aies pas rencontré ce problème @REMYJulien du coup je pense que tu l'as déjà résolu sans push les changements.

**Comment by Schluucht** [comment]
fix #2
