### ISSUE TITLE
Object Relational implementation

### ISSUE THREAD

**Issue by lucgiffon** [Schluucht/Destiny#6]
Use sqlalchemy or any other ORM framework in order to manipulate data.

- Create one model for each table

Should we change the current implementation of data retrieving?

**Comment by lucgiffon** [comment]
Atm, the tables are not linked together through foreign key relationships. I'm drawing the mcd on dia in order to get a better visualization of the whole thing. Dia is an open source software for drawing diagrams: https://fr.wikipedia.org/wiki/Dia_(logiciel). But dia files are binaries. It is not nice for git.

**Comment by lucgiffon** [comment]
Aren't the tables assistEvent, victimEvent and killEvent redoundant?

**Comment by Schluucht** [comment]
@lucgiffon  ```  But dia files are binaries. It is not nice for git.   ``` What about export them as png and create wiki for Destiny project ?

**Comment by lucgiffon** [comment]
png files still are binaries and they don't have the advantage to be readable by dia and be modified in place easily.
The wiki idea remains and it would be nice to have 1. Nevertheless, I don't think it is a priority now and I won't be in charge for this. We can raise an issue, tho.

**Comment by lucgiffon** [comment]
There is a working version in the branch orm_implementation. Waiting for updating architecture before merge in develop
